<?php

$repo = 'https://github.com/HarshitBhatt043/Jenkins-Project-Web-Arcade.git';

$games = [
    'hextris-lite' => [
        'name' => 'Hexagonal',
        'tag' => 'tetris',
        'git' => $repo,
        'branch' => 'hextris-lite',
        'mobile' => true,
        'desktop' => true,
    ],
    'pond-lite' => [
        'name' => 'Pond',
        'tag' => 'eat, swim',
        'git' => $repo,
        'branch' => 'pond-lite',
        'mobile' => true,
        'desktop' => true,
    ],
    '2048-lite' => [
        'name' => '2, 4, 8',
        'tag' => 'swipe',
        'git' => $repo,
        'branch' => '2048',
        'mobile' => true,
        'desktop' => true,
    ],
    '0hh1' => [
        'name' => 'Fill',
        'tag' => 'the grid',
        'git' => $repo,
        'branch' => '0hh1',
        'mobile' => true,
        'desktop' => true,
    ],
    'HexGL' => [
        'name' => 'Racing',
        'tag' => 'pod',
        'git' => $repo,
        'branch' => 'HexGL',
        'mobile' => true,
        'desktop' => true,
    ],
    'floppybird' => [
        'name' => 'Flappy',
        'tag' => ' bird',
        'git' => $repo,
        'branch' => 'floppybird',
        'mobile' => true,
        'desktop' => true,
    ],
    'NS-SHAFT' => [
        'name' => 'Fall',
        'tag' => 'safely',
        'git' => $repo,
        'branch' => 'NS-SHAFT',
        'mobile' => true,
        'desktop' => true,
    ],
    'parity' => [
        'name' => 'Numbers',
        'tag' => 'puzzle',
        'git' => $repo,
        'branch' => 'parity',
        'mobile' => true,
        'desktop' => true,
    ],
    'hexahedral' => [
        'name' => 'Push',
        'tag' => 'all the blocks',
        'git' => $repo,
        'branch' => 'hexahedral',
        'mobile' => true,
        'desktop' => true,
    ],
    'swipe-brick-breaker' => [
        'name' => 'Brick Break',
        'tag' => 'easy',
        'git' => $repo,
        'branch' => 'swipe-brick-breaker',
        'mobile' => true,
        'desktop' => true,
    ],
    'taptaptap' => [
        'name' => 'Tap',
        'tag' => 'the blue',
        'git' => $repo,
        'branch' => 'taptaptap',
        'mobile' => true,
        'desktop' => true,
    ],
    'particle-clicker' => [
        'name' => 'Particle',
        'tag' => 'clicker',
        'git' => $repo,
        'branch' => 'particle-clicker',
        'mobile' => true,
        'desktop' => true,
    ],
    '3d.city' => [
        'name' => 'Build',
        'tag' => 'the city',
        'git' => $repo,
        'branch' => '3d.city',
        'mobile' => false,
        'desktop' => true,
    ],
    'fire-n-ice' => [
        'name' => 'Fire and ice',
        'tag' => 'NES remake',
        'git' => $repo,
        'branch' => 'fire-n-ice',
        'mobile' => true,
        'desktop' => true,
    ],
    'paint-run2' => [
        'name' => 'Turn',
        'tag' => ' the tiles blue',
        'git' => $repo,
        'branch' => 'paint-run2',
        'mobile' => false,
        'desktop' => true,
    ],
    'tower_game' => [
        'name' => 'Build',
        'tag' => 'highest tower',
        'git' => $repo,
        'branch' => 'tower_game',
        'mobile' => true,
        'desktop' => true,
    ],
    'Hyperspace-Garbage' => [
        'name' => 'Garbage',
        'tag' => 'collect',
        'git' => $repo,
        'branch' => 'Hyperspace-Garbage',
        'mobile' => true,
        'desktop' => true,
    ],
    'pacman-lite' => [
        'name' => 'Pacman',
        'tag' => '2d',
        'git' => $repo,
        'branch' => 'pacman-lite',
        'mobile' => true,
        'desktop' => true,
    ],
    'missile' => [
        'name' => 'Missile',
        'tag' => 'dodge',
        'git' => $repo,
        'branch' => 'missile',
        'mobile' => true,
        'desktop' => true,
    ],
    'Temple_Run_2' => [
        'name' => 'Take',
        'tag' => 'the idol',
        'git' => $repo,
        'branch' => 'Temple_Run_2',
        'mobile' => true,
        'desktop' => true,
    ],
    '99-Balls' => [
        'name' => 'Brick Break',
        'tag' => 'hard',
        'git' => $repo,
        'branch' => '99-Balls',
        'mobile' => true,
        'desktop' => true,
    ],
    'Dino' => [
        'name' => 'Dino',
        'tag' => 'run',
        'git' => $repo,
        'branch' => 'Dino',
        'mobile' => true,
        'desktop' => true,
    ],
    'Tanuki-sunset' => [
        'name' => 'Tanuki',
        'tag' => 'sunset',
        'git' => $repo,
        'branch' => 'Tanuki-sunset',
        'mobile' => false,
        'desktop' => true,
    ],
    'Elasticman' => [
        'name' => 'Elastic',
        'tag' => 'face',
        'git' => $repo,
        'branch' => 'Elasticman',
        'mobile' => true,
        'desktop' => true,
    ],
    'Subway-SF' => [
        'name' => 'San',
        'tag' => 'francisco',
        'git' => $repo,
        'branch' => 'Subway-SF',
        'mobile' => true,
        'desktop' => true,
    ],
    'Subway-NY' => [
        'name' => 'New York',
        'tag' => 'hard version',
        'git' => $repo,
        'branch' => 'Subway-NY',
        'mobile' => true,
        'desktop' => true,
    ],
    'Fruit-ninja' => [
        'name' => 'Slice',
        'tag' => 'fruits',
        'git' => $repo,
        'branch' => 'Fruit-ninja',
        'mobile' => true,
        'desktop' => true,
    ],
    'Fruit-ninja2' => [
        'name' => 'Slice',
        'tag' => 'more fruits',
        'git' => $repo,
        'branch' => 'Fruit-ninja2',
        'mobile' => true,
        'desktop' => true,
    ],
    'Rocket-League' => [
        'name' => 'Do',
        'tag' => 'maximum goals',
        'git' => $repo,
        'branch' => 'Rocket-League',
        'mobile' => false,
        'desktop' => true,
    ],
    'Pacman-3d' => [
        'name' => 'Pacman',
        'tag' => '3d',
        'git' => $repo,
        'branch' => 'Pacman-3d',
        'mobile' => true,
        'desktop' => true,
    ],
    'Time-Sphere' => [
        'name' => 'Draw',
        'tag' => 'and win',
        'git' => $repo,
        'branch' => 'Time-Sphere',
        'mobile' => true,
        'desktop' => true,
    ],
    'Adventure-Drivers' => [
        'name' => 'Win',
        'tag' => 'the race',
        'git' => $repo,
        'branch' => 'Adventure-Drivers',
        'mobile' => true,
        'desktop' => true,
    ],
    'Cluster-Rush' => [
        'name' => 'Jump',
        'tag' => 'over trucks',
        'git' => $repo,
        'branch' => 'Cluster-Rush',
        'mobile' => false,
        'desktop' => true,
    ],
    'Color-Switch' => [
        'name' => 'Tap',
        'tag' => 'and pass',
        'git' => $repo,
        'branch' => 'Color-Switch',
        'mobile' => true,
        'desktop' => true,
    ],
    'Connect-3' => [
        'name' => 'Match',
        'tag' => 'three',
        'git' => $repo,
        'branch' => 'Connect-3',
        'mobile' => true,
        'desktop' => true,
    ],
    'Dragon-Bricks' => [
        'name' => 'Break',
        'tag' => 'through blocks',
        'git' => $repo,
        'branch' => 'Dragon-Bricks',
        'mobile' => true,
        'desktop' => true,
    ],
    'Drift-Boss' => [
        'name' => 'Drift',
        'tag' => 'through',
        'git' => $repo,
        'branch' => 'Drift-Boss',
        'mobile' => true,
        'desktop' => true,
    ],
    'Core-Ball' => [
        'name' => 'How many',
        'tag' => 'can u plant',
        'git' => $repo,
        'branch' => 'Core-Ball',
        'mobile' => true,
        'desktop' => true,
    ],
    'Car-Simulator' => [
        'name' => 'Experience',
        'tag' => 'simulation',
        'git' => $repo,
        'branch' => 'Car-Simulator',
        'mobile' => false,
        'desktop' => true,
    ],
    'Battle-Stone' => [
        'name' => 'Lets',
        'tag' => 'fight',
        'git' => $repo,
        'branch' => 'Battle-Stone',
        'mobile' => false,
        'desktop' => true,
    ],
    'Slime' => [
        'name' => 'Jump',
        'tag' => 'to finish line',
        'git' => $repo,
        'branch' => 'Slime',
        'mobile' => true,
        'desktop' => true,
    ],
    'Drift-Hunters' => [
        'name' => 'Drift',
        'tag' => 'and unlock new',
        'git' => $repo,
        'branch' => 'Drift-Hunters',
        'mobile' => false,
        'desktop' => true,
    ],
    'Townscaper' => [
        'name' => 'Build',
        'tag' => 'imagination',
        'git' => $repo,
        'branch' => 'Townscaper',
        'mobile' => true,
        'desktop' => true,
    ],
    'Scrapmetal-3' => [
        'name' => 'Destroy car',
        'tag' => 'simulation',
        'git' => $repo,
        'branch' => 'Scrapmetal-3',
        'mobile' => false,
        'desktop' => true,
    ],
    'Superhot' => [
        'name' => 'Time is',
        'tag' => 'everything',
        'git' => $repo,
        'branch' => 'Superhot',
        'mobile' => false,
        'desktop' => true,
    ],
    'Kitchen-Gun' => [
        'name' => 'shoot',
        'tag' => 'items',
        'git' => $repo,
        'branch' => 'Kitchen-Gun',
        'mobile' => false,
        'desktop' => true,
    ],
    'Madalin-Stuntcars-2' => [
        'name' => 'Race car',
        'tag' => 'simulator',
        'git' => $repo,
        'branch' => 'Madalin-Stuntcars-2',
        'mobile' => false,
        'desktop' => true,
    ],
    'Station-141' => [
        'name' => 'Station 141',
        'tag' => 'shooting',
        'git' => $repo,
        'branch' => 'Station-141',
        'mobile' => false,
        'desktop' => true,
    ],
    'Game-Inside' => [
        'name' => 'Game Inside',
        'tag' => 'Game',
        'git' => $repo,
        'branch' => 'Game-Inside',
        'mobile' => false,
        'desktop' => true,
    ],
    'Dance-Fire-and-Ice' => [
        'name' => 'Dance-Fire-and-Ice',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Dance-Fire-and-Ice',
        'mobile' => false,
        'desktop' => true,
    ],
    'Alien-Invasion-Open' => [
        'name' => 'Alien-Invasion-Open',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Alien-Invasion-Open',
        'mobile' => false,
        'desktop' => true,
    ],
    'Virtuous-Run' => [
        'name' => 'Virtuous-Run',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Virtuous-Run',
        'mobile' => false,
        'desktop' => true,
    ],
    'Awesometanks' => [
        'name' => 'Awesometanks',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Awesometanks',
        'mobile' => false,
        'desktop' => true,
    ],
    'Awesometanks2' => [
        'name' => 'Awesometanks2',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Awesometanks2',
        'mobile' => false,
        'desktop' => true,
    ],
    'Bacon-May-Die' => [
        'name' => 'Bacon-May-Die',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Bacon-May-Die',
        'mobile' => false,
        'desktop' => true,
    ],
    'Ballistic-Chickens' => [
        'name' => 'Ballistic-Chickens',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Ballistic-Chickens',
        'mobile' => false,
        'desktop' => true,
    ],
    'Blacholesquare' => [
        'name' => 'Blacholesquare',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Blacholesquare',
        'mobile' => false,
        'desktop' => true,
    ],
    'Bloons-td4' => [
        'name' => 'Bloons-td4',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Bloons-td4',
        'mobile' => false,
        'desktop' => true,
    ],
    'Candy-Crush' => [
        'name' => 'Candy-Crush',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Candy-Crush',
        'mobile' => false,
        'desktop' => true,
    ],
    'Circlo' => [
        'name' => 'Circlo',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Circlo',
        'mobile' => false,
        'desktop' => true,
    ],
    'Craftmine' => [
        'name' => 'Craftmine',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Craftmine',
        'mobile' => false,
        'desktop' => true,
    ],
    'Crossyroad-Normal' => [
        'name' => 'Crossyroad-Normal',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Crossyroad-Normal',
        'mobile' => false,
        'desktop' => true,
    ],
    'Crossyroad-Sace' => [
        'name' => 'Crossyroad-Sace',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Crossyroad-Sace',
        'mobile' => false,
        'desktop' => true,
    ],
    'Cut-The-Rope' => [
        'name' => 'Cut-The-Rope',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Cut-The-Rope',
        'mobile' => false,
        'desktop' => true,
    ],
    'Cut-The-Rope-Holiday' => [
        'name' => 'Cut-The-Rope-Holiday',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Cut-The-Rope-Holiday',
        'mobile' => false,
        'desktop' => true,
    ],
    'Cut-The-Rope-Time-Travel' => [
        'name' => 'Cut-The-Rope-Time-Travel',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Cut-The-Rope-Time-Travel',
        'mobile' => false,
        'desktop' => true,
    ],
    'Cut-The-Rope-Vivid' => [
        'name' => 'Cut-The-Rope-Vivid',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Cut-The-Rope-Vivid',
        'mobile' => false,
        'desktop' => true,
    ],
    'Cubefield' => [
        'name' => 'Cubefield',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Cubefield',
        'mobile' => false,
        'desktop' => true,
    ],
    'Dante' => [
        'name' => 'Dante',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Dante',
        'mobile' => false,
        'desktop' => true,
    ],
    'Death-Run-3d' => [
        'name' => 'Death-Run-3d',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Death-Run-3d',
        'mobile' => false,
        'desktop' => true,
    ],
    'Doodle-Jump' => [
        'name' => 'Doodle-Jump',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Doodle-Jump',
        'mobile' => false,
        'desktop' => true,
    ],
    'Draw-the-Hill' => [
        'name' => 'Draw-the-Hill',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Draw-the-Hill',
        'mobile' => false,
        'desktop' => true,
    ],
    'Drive-Mad' => [
        'name' => 'Drive-Mad',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Drive-Mad',
        'mobile' => false,
        'desktop' => true,
    ],
    'Earn-to-Die' => [
        'name' => 'Earn-to-Die',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Earn-to-Die',
        'mobile' => false,
        'desktop' => true,
    ],
    'Eggy-Car' => [
        'name' => 'Eggy-Car',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Eggy-Car',
        'mobile' => false,
        'desktop' => true,
    ],
    'Evade' => [
        'name' => 'Evade',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Evade',
        'mobile' => false,
        'desktop' => true,
    ],
    'Evil-Glitch' => [
        'name' => 'Evil-Glitch',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Evil-Glitch',
        'mobile' => false,
        'desktop' => true,
    ],
    'Fairsquares' => [
        'name' => 'Fairsquares',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Fairsquares',
        'mobile' => false,
        'desktop' => true,
    ],
    'Fallguys' => [
        'name' => 'Fallguys',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Fallguys',
        'mobile' => false,
        'desktop' => true,
    ],
    'Fluid-Simulation' => [
        'name' => 'Fluid-Simulation',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Fluid-Simulation',
        'mobile' => false,
        'desktop' => true,
    ],
    'Geodash' => [
        'name' => 'Geodash',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Geodash',
        'mobile' => false,
        'desktop' => true,
    ],
    'Ghostwalker' => [
        'name' => 'Ghostwalker',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Ghostwalker',
        'mobile' => false,
        'desktop' => true,
    ],
    'Happy-Glass' => [
        'name' => 'Happy-Glass',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Happy-Glass',
        'mobile' => false,
        'desktop' => true,
    ],
    'Happy-Hop' => [
        'name' => 'Happy-Hop',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Happy-Hop',
        'mobile' => false,
        'desktop' => true,
    ],
    'Helixjump' => [
        'name' => 'Helixjump',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Helixjump',
        'mobile' => false,
        'desktop' => true,
    ],
    'Hill-Racing' => [
        'name' => 'Hill-Racing',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Hill-Racing',
        'mobile' => false,
        'desktop' => true,
    ],
    'Minesweeper' => [
        'name' => 'Minesweeper',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Minesweeper',
        'mobile' => false,
        'desktop' => true,
    ],
    'Jetpack-Joyride' => [
        'name' => 'Jetpack-Joyride',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Jetpack-Joyride',
        'mobile' => false,
        'desktop' => true,
    ],
    'MonkeyMart' => [
        'name' => 'MonkeyMart',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'MonkeyMart',
        'mobile' => false,
        'desktop' => true,
    ],
    'Monster-Tracks' => [
        'name' => 'Monster-Tracks',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Monster-Tracks',
        'mobile' => false,
        'desktop' => true,
    ],
    'Motox3m' => [
        'name' => 'Motox3m',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Motox3m',
        'mobile' => false,
        'desktop' => true,
    ],
    'Motox3m2' => [
        'name' => 'Motox3m2',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Motox3m2',
        'mobile' => false,
        'desktop' => true,
    ],
    'Motox3m-Pool' => [
        'name' => 'Motox3m-Pool',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Motox3m-Pool',
        'mobile' => false,
        'desktop' => true,
    ],
    'Motox3m-Spooky' => [
        'name' => 'Motox3m-Spooky',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Motox3m-Spooky',
        'mobile' => false,
        'desktop' => true,
    ],
    'Motox3m-Winter' => [
        'name' => 'Motox3m-Winter',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Motox3m-Winter',
        'mobile' => false,
        'desktop' => true,
    ],
    'Om-Bounce' => [
        'name' => 'Om-Bounce',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Om-Bounce',
        'mobile' => false,
        'desktop' => true,
    ],
    'Omnom-Run' => [
        'name' => 'Omnom-Run',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Omnom-Run',
        'mobile' => false,
        'desktop' => true,
    ],
    'Paperio2' => [
        'name' => 'Paperio2',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Paperio2',
        'mobile' => false,
        'desktop' => true,
    ],
    'Paperio3d' => [
        'name' => 'Paperio3d',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Paperio3d',
        'mobile' => false,
        'desktop' => true,
    ],
    'Papery-Planes' => [
        'name' => 'Papery-Planes',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Papery-Planes',
        'mobile' => false,
        'desktop' => true,
    ],
    'Pickaxe-Tower' => [
        'name' => 'Pickaxe-Tower',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Pickaxe-Tower',
        'mobile' => false,
        'desktop' => true,
    ],
    'Pixel-Gun-Survival' => [
        'name' => 'Pixel-Gun-Survival',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Pixel-Gun-Survival',
        'mobile' => false,
        'desktop' => true,
    ],
    'PushTheBox' => [
        'name' => 'PushTheBox',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'PushTheBox',
        'mobile' => false,
        'desktop' => true,
    ],
    'Plant-vs-Zombies' => [
        'name' => 'Plant-vs-Zombies',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Plant-vs-Zombies',
        'mobile' => false,
        'desktop' => true,
    ],
    'Recoil' => [
        'name' => 'Recoil',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Recoil',
        'mobile' => false,
        'desktop' => true,
    ],
    'Rolling-Forests' => [
        'name' => 'Rolling-Forests',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Rolling-Forests',
        'mobile' => false,
        'desktop' => true,
    ],
    'Rooftop-Snipers-2' => [
        'name' => 'Rooftop-Snipers-2',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Rooftop-Snipers-2',
        'mobile' => false,
        'desktop' => true,
    ],
    'Sand-Game' => [
        'name' => 'Sand-Game',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Sand-Game',
        'mobile' => false,
        'desktop' => true,
    ],
    'Skyjunk' => [
        'name' => 'Skyjunk',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Skyjunk',
        'mobile' => false,
        'desktop' => true,
    ],
    'Slime-Rush-Td' => [
        'name' => 'Slime-Rush-Td',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Slime-Rush-Td',
        'mobile' => false,
        'desktop' => true,
    ],
    'SlingTomb' => [
        'name' => 'SlingTomb',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'SlingTomb',
        'mobile' => false,
        'desktop' => true,
    ],
    'Slope' => [
        'name' => 'Slope',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Slope',
        'mobile' => false,
        'desktop' => true,
    ],
    'Slope-2' => [
        'name' => 'Slope-2',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Slope-2',
        'mobile' => false,
        'desktop' => true,
    ],
    'Slope-Ball' => [
        'name' => 'Slope-Ball',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Slope-Ball',
        'mobile' => false,
        'desktop' => true,
    ],
    'Snowbattle' => [
        'name' => 'Snowbattle',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Snowbattle',
        'mobile' => false,
        'desktop' => true,
    ],
    'Soldier-Legend' => [
        'name' => 'Soldier-Legend',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Soldier-Legend',
        'mobile' => false,
        'desktop' => true,
    ],
    'Stack' => [
        'name' => 'Stack',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Stack',
        'mobile' => false,
        'desktop' => true,
    ],
    'Stack-Bump-3D' => [
        'name' => 'Stack-Bump-3D',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Stack-Bump-3D',
        'mobile' => false,
        'desktop' => true,
    ],
    'Stair-Race-3d' => [
        'name' => 'Stair-Race-3d',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Stair-Race-3d',
        'mobile' => false,
        'desktop' => true,
    ],
    'Stick-Duel-Battle' => [
        'name' => 'Stick-Duel-Battle',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Stick-Duel-Battle',
        'mobile' => false,
        'desktop' => true,
    ],
    'Stickman-Boost' => [
        'name' => 'Stickman-Boost',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Stickman-Boost',
        'mobile' => false,
        'desktop' => true,
    ],
    'Stickman-Golf' => [
        'name' => 'Stickman-Golf',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Stickman-Golf',
        'mobile' => false,
        'desktop' => true,
    ],
    'Stickman-Hook' => [
        'name' => 'Stickman-Hook',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Stickman-Hook',
        'mobile' => false,
        'desktop' => true,
    ],
    'Superfowlist' => [
        'name' => 'Superfowlist',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Superfowlist',
        'mobile' => false,
        'desktop' => true,
    ],
    'Swingo' => [
        'name' => 'Swingo',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Swingo',
        'mobile' => false,
        'desktop' => true,
    ],
    'Synth' => [
        'name' => 'Synth',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Synth',
        'mobile' => false,
        'desktop' => true,
    ],
    'Tank-Trouble-2' => [
        'name' => 'Tank-Trouble-2',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Tank-Trouble-2',
        'mobile' => false,
        'desktop' => true,
    ],
    'The-Hotel' => [
        'name' => 'The-Hotel',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'The-Hotel',
        'mobile' => false,
        'desktop' => true,
    ],
    'Tiny-Fishing' => [
        'name' => 'Tiny-Fishing',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Tiny-Fishing',
        'mobile' => false,
        'desktop' => true,
    ],
    'Tunnel-Rush' => [
        'name' => 'Tunnel-Rush',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Tunnel-Rush',
        'mobile' => false,
        'desktop' => true,
    ],
    'Underrun' => [
        'name' => 'Underrun',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Underrun',
        'mobile' => false,
        'desktop' => true,
    ],
    'Uno' => [
        'name' => 'Uno',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Uno',
        'mobile' => false,
        'desktop' => true,
    ],
    'Uvsu' => [
        'name' => 'Uvsu',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Uvsu',
        'mobile' => false,
        'desktop' => true,
    ],
    'Veloce' => [
        'name' => 'Veloce',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Veloce',
        'mobile' => false,
        'desktop' => true,
    ],
    'Vex3' => [
        'name' => 'Vex3',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Vex3',
        'mobile' => false,
        'desktop' => true,
    ],
    'Vex4' => [
        'name' => 'Vex4',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Vex4',
        'mobile' => false,
        'desktop' => true,
    ],
    'Vex5' => [
        'name' => 'Vex5',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Vex5',
        'mobile' => false,
        'desktop' => true,
    ],
    'Vex6' => [
        'name' => 'Vex6',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Vex6',
        'mobile' => false,
        'desktop' => true,
    ],
    'Vex7' => [
        'name' => 'Vex7',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Vex7',
        'mobile' => false,
        'desktop' => true,
    ],
    'Weavesilk' => [
        'name' => 'Weavesilk',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Weavesilk',
        'mobile' => false,
        'desktop' => true,
    ],
    'Wordle' => [
        'name' => 'Wordle',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'Wordle',
        'mobile' => false,
        'desktop' => true,
    ],
    'X-Trial-Racing' => [
        'name' => 'X-Trial-Racing',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'X-Trial-Racing',
        'mobile' => false,
        'desktop' => true,
    ],
    'ZombieDerby' => [
        'name' => 'ZombieDerby',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'ZombieDerby',
        'mobile' => false,
        'desktop' => true,
    ],
    'ZombieDerby2' => [
        'name' => 'ZombieDerby2',
        'tag' => 'check',
        'git' => $repo,
        'branch' => 'ZombieDerby2',
        'mobile' => false,
        'desktop' => true,
    ],
];
