<?php

$repo = 'https://github.com/HarshitBhatt043/Jenkins-Project-Web-Arcade.git';

$games = [
    'hextris' => [
        'name'    => 'Hextris',
        'tag'     => 'hexagonal tetris',
        'git'     => $repo,
        'branch'  => 'hextris-lite',
        'mobile'  => true,
        'desktop' => true,
    ],
    'pond' => [
        'name'    => 'The Pond',
        'tag'     => 'eat, swim, love',
        'git'     => $repo,
        'branch'  => 'pond-lite',
        'mobile'  => true,
        'desktop' => true,
    ],
    '2048-lite' => [
        'name'    => '2048',
        'tag'     => '2, 4, 8, swipe',
        'git'     => $repo,
        'branch'  => '2048',
        'mobile'  => true,
        'desktop' => true,
    ],
    '0hh1' => [
        'name'    => '0hh1',
        'tag'     => 'fill the grid',
        'git'     => $repo,
        'branch'  => '0hh1',
        'mobile'  => true,
        'desktop' => true,
    ],
    'hexgl' => [
        'name'    => 'HexGL',
        'tag'     => 'racing pod',
        'git'     => $repo,
        'branch'  => 'HexGL',
        'mobile'  => true,
        'desktop' => true,
    ],
    'clumsy-bird' => [
        'name'    => 'Clumsy Bird',
        'tag'     => 'flappy Bird',
        'git'     => $repo, 
        'branch'  => 'floppybird', 
        'mobile'  => true,
        'desktop' => true,
    ],
    'ns-shaft' => [
        'name'    => 'NS Shaft',
        'tag'     => 'fall safely',
        'git'     => $repo,        
        'branch'  => 'NS-SHAFT',        
        'mobile'  => true,
        'desktop' => true,
    ],
    'parity' => [
        'name'    => 'Parity',
        'tag'     => 'numbers puzzle',
        'git'     => $repo,        
        'branch'  => 'parity',        
        'mobile'  => true,
        'desktop' => true,
    ],
    'hexahedral' => [
        'name'    => 'Hexahedral',
        'tag'     => 'push all blocks',
        'git'     => $repo,        
        'branch'  => 'hexahedral',        
        'mobile'  => true,
        'desktop' => true,
    ],
    'swipe-brick-breaker' => [
        'name'    => 'Brick Breaker',
        'tag'     => 'swipe and break',
        'git'     => $repo,        
        'branch'  => 'swipe-brick-breaker',        
        'mobile'  => true,
        'desktop' => true,
    ],
    'taptaptap' => [
        'name'    => 'Tap Tap',
        'tag'     => 'tap the blue',
        'git'     => $repo,        
        'branch'  => 'taptaptap',        
        'mobile'  => true,
        'desktop' => true,
    ],
    'particle-clicker' => [
        'name'    => 'Clicker',
        'tag'     => 'history particle physics',
        'git'     => $repo,        
        'branch'  => 'particle-clicker',        
        'mobile'  => true,
        'desktop' => true,
    ],
    '3d.city' => [
        'name'    => '3d City',
        'tag'     => 'builder game',
        'git'     => $repo,        
        'branch'  => '3d.city',        
        'mobile'  => false,
        'desktop' => true,
    ],
    'fire-n-ice' => [
        'name'    => 'Fire and ice',
        'tag'     => 'remake of NES game',
        'git'     => $repo,        
        'branch'  => 'fire-n-ice',        
        'mobile'  => true,
        'desktop' => true,
    ],
    'paint-run2' => [
        'name'    => 'Paint Run',
        'tag'     => 'turn tiles blue',
        'git'     => $repo,        
        'branch'  => 'paint-run2',        
        'mobile'  => false,
        'desktop' => true,
    ],
    'tower_game' => [
        'name'    => 'Tower',
        'tag'     => 'build tower',
        'git'     => $repo,        
        'branch'  => 'tower_game',        
        'mobile'  => true,
        'desktop' => true,
    ],
    'Hyperspace-Garbage' => [
        'name'    => 'Hyperspace Garbage',
        'tag'     => 'manipulate trash',
        'git'     => $repo,        
        'branch'  => 'Hyperspace-Garbage',        
        'mobile'  => true,
        'desktop' => true,
    ],
    'pacman-lite' => [
        'name'    => 'Pacman',
        'tag'     => 'pacman game',
        'git'     => $repo,        
        'branch'  => 'pacman-lite',        
        'mobile'  => true,
        'desktop' => true,
    ],
];
