<?php

$games = [
    'hextris' => [
        'name'    => 'Hextris',
        'tag'     => 'hexagonal tetris',
        'git'     => 'https://github.com/HarshitBhatt043/Jenkins-Project-Web-Arcade.git',
        'branch'  => 'hextris-lite',
        'mobile'  => true,
        'desktop' => true,
    ],
    'pond' => [
        'name'    => 'The Pond',
        'tag'     => 'eat, swim, love',
        'git'     => 'https://github.com/HarshitBhatt043/Jenkins-Project-Web-Arcade.git',
        'branch'  => 'pond-lite',
        'mobile'  => true,
        'desktop' => true,
    ],
    '2048-lite' => [
        'name'    => '2048',
        'tag'     => '2, 4, 8, swipe',
        'git'     => 'https://github.com/HarshitBhatt043/Jenkins-Project-Web-Arcade.git',
        'branch'  => '2048',
        'mobile'  => true,
        'desktop' => true,
    ],
    '0hh1' => [
        'name'    => '0hh1',
        'tag'     => 'tap the blue',
        'git'     => 'https://github.com/HarshitBhatt043/Jenkins-Project-Web-Arcade.git',
        'branch'  => '0hh1',
        'mobile'  => true,
        'desktop' => true,
    ],
    'hexgl' => [
        'name'    => 'HexGL',
        'tag'     => 'racing pod',
        'git'     => 'https://github.com/HarshitBhatt043/Jenkins-Project-Web-Arcade.git',
        'branch'  => 'HexGL',
        'mobile'  => true,
        'desktop' => true,
    ],
    'clumsy-bird' => [
        'name'    => 'Clumsy Bird',
        'tag'     => 'flappy happy',
        'git'     => 'https://github.com/HarshitBhatt043/Jenkins-Project-Web-Arcade.git',
        'branch'  => 'floppybird', 
        'mobile'  => true,
        'desktop' => true,
    ],
    'ns-shaft' => [
        'name'    => 'NS-Shaft',
        'tag'     => 'fall safely',
        'git'     => 'https://github.com/HarshitBhatt043/Jenkins-Project-Web-Arcade.git',
        'branch'  => 'NS-SHAFT',        
        'mobile'  => true,
        'desktop' => true,
    ],
    'parity' => [
        'name'    => 'parity',
        'tag'     => 'fall safely',
        'git'     => 'https://github.com/HarshitBhatt043/Jenkins-Project-Web-Arcade.git',
        'branch'  => 'parity',        
        'mobile'  => true,
        'desktop' => true,
    ],
    'hexahedral' => [
        'name'    => 'hexahedral',
        'tag'     => 'fall safely',
        'git'     => 'https://github.com/HarshitBhatt043/Jenkins-Project-Web-Arcade.git',
        'branch'  => 'hexahedral',        
        'mobile'  => true,
        'desktop' => true,
    ],
    'swipe-brick-breaker' => [
        'name'    => 'swipe-brick-breaker',
        'tag'     => 'fall safely',
        'git'     => 'https://github.com/HarshitBhatt043/Jenkins-Project-Web-Arcade.git',
        'branch'  => 'swipe-brick-breaker',        
        'mobile'  => true,
        'desktop' => true,
    ],
    'taptaptap' => [
        'name'    => 'taptaptap',
        'tag'     => 'fall safely',
        'git'     => 'https://github.com/HarshitBhatt043/Jenkins-Project-Web-Arcade.git',
        'branch'  => 'taptaptap',        
        'mobile'  => true,
        'desktop' => true,
    ],
    'particle-clicker' => [
        'name'    => 'particle-clicker',
        'tag'     => 'fall safely',
        'git'     => 'https://github.com/HarshitBhatt043/Jenkins-Project-Web-Arcade.git',
        'branch'  => 'particle-clicker',        
        'mobile'  => true,
        'desktop' => true,
    ],
    '3d.city' => [
        'name'    => '3d.city',
        'tag'     => 'fall safely',
        'git'     => 'https://github.com/HarshitBhatt043/Jenkins-Project-Web-Arcade.git',
        'branch'  => '3d.city',        
        'mobile'  => false,
        'desktop' => true,
    ],
    'fire-n-ice' => [
        'name'    => 'fire-n-ice',
        'tag'     => 'fall safely',
        'git'     => 'https://github.com/HarshitBhatt043/Jenkins-Project-Web-Arcade.git',
        'branch'  => 'fire-n-ice',        
        'mobile'  => true,
        'desktop' => true,
    ],
    'paint-run2' => [
        'name'    => 'paint-run2',
        'tag'     => 'fall safely',
        'git'     => 'https://github.com/HarshitBhatt043/Jenkins-Project-Web-Arcade.git',
        'branch'  => 'paint-run2',        
        'mobile'  => false,
        'desktop' => true,
    ],
    'tower_game' => [
        'name'    => 'tower_game',
        'tag'     => 'fall safely',
        'git'     => 'https://github.com/HarshitBhatt043/Jenkins-Project-Web-Arcade.git',
        'branch'  => 'tower_game',        
        'mobile'  => true,
        'desktop' => true,
    ],
    'Hyperspace-Garbage' => [
        'name'    => 'Hyperspace-Garbage',
        'tag'     => 'fall safely',
        'git'     => 'https://github.com/HarshitBhatt043/Jenkins-Project-Web-Arcade.git',
        'branch'  => 'Hyperspace-Garbage',        
        'mobile'  => true,
        'desktop' => true,
    ],
    'pacman-lite' => [
        'name'    => 'pacman-lite',
        'tag'     => 'fall safely',
        'git'     => 'https://github.com/HarshitBhatt043/Jenkins-Project-Web-Arcade.git',
        'branch'  => 'pacman-lite',        
        'mobile'  => true,
        'desktop' => true,
    ],
];