version: "3.9"
services:
  arcade:
    image: harshitbhatt043/arcade:latest
    user: "1001:1001"
    container_name: arcade
    ports:
      - 5000:80
    restart: unless-stopped
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    network_mode: "host"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--enable-feature=agent'
    restart: unless-stopped