version: 2.1

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

jobs:
  build:
    docker:
      - image: node:latest
    steps:
      - run:
          name: Clonning Code
          command: git clone --single-branch --depth 1 -b "$CIRCLE_BRANCH" << pipeline.trigger_parameters.github_app.repo_url >> "$CIRCLE_WORKING_DIRECTORY"
      - sonarcloud/scan
